services:
  - type: web
    name: duo-life-sms-webhook
    runtime: node
    rootDir: webhook-server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: Node.js v20.20.2
        value: "20"
      - key: duo_acc_72341824ss2004
        generateValue: true
      - key: 12345a6789b101112131415c
        sync: false
